version: '3'

networks:
  job-compiler:
    name: job-compiler
    external: true


volumes:
  my_static_volume:


services:
  worker1:
    build:
      context: ./
    container_name: worker1
    hostname: worker1
    networks:
      - job-compiler
    volumes:
      - my_static_volume:/app/staticfiles

  worker2:
    build:
      context: ./
    container_name: worker2
    hostname: worker2
    networks:
      - job-compiler
    volumes:
      - my_static_volume:/app/staticfiles

  load-balancer:
    build:
      context: ./nginx-container
    container_name: load-balancer
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - worker1
      - worker2
    networks:
      - job-compiler
    volumes:
      - ./nginx-container/ssl:/etc/nginx/ssl
      - my_static_volume:/var/www/static
