version: '3'

networks:
  job-compiler:
    name: job-compiler
    external: true

services:
  worker1:
    build:
      context: ./
    container_name: worker1
    hostname: worker1
    networks:
      - job-compiler

  worker2:
    build:
      context: ./
    container_name: worker2
    hostname: worker2
    networks:
      - job-compiler

  load-balancer:
    build:
      context: ../nginx-container
    container_name: load-balancer
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - worker1
      - worker2
    networks:
      - job-compiler
    volumes:
      - /home/ubuntu/nginx-container/ssl:/etc/nginx/ssl
